Properly handling more than one ScummVM game in the same folder

diff --git a/board/batocera/fsoverlay/usr/bin/knulli-detect-scummvm-game b/board/batocera/fsoverlay/usr/bin/knulli-detect-scummvm-game
--- a/board/batocera/fsoverlay/usr/bin/knulli-detect-scummvm-game
+++ b/board/batocera/fsoverlay/usr/bin/knulli-detect-scummvm-game
@@ -38,24 +38,35 @@ echo "$GAME_FOLDER has no ScummVM file, yet - attempting game detection."
 
 # Add game to libretro ScummVM config and memorize the game handle and name
 ADDING_GAME_LOG="$(scummvm -c "$LIBRETRO_SCUMMVM_INI" -p "$GAME_FOLDER" --add)"
-GAME_HANDLE="$(sed -En "s/[ ]*Target:[ ]*(.*)/\1/p" <<< $ADDING_GAME_LOG)"
+GAME_HANDLES_RAW="$(sed -En "s/[ ]*Target:[ ]*(.*)/\1/p" <<< $ADDING_GAME_LOG)"
+GAME_NAMES_RAW="$(sed -En "s/[ ]*Name:[ ]*(.*)/\1/p" <<< $ADDING_GAME_LOG)"
 
-if [ -z "$GAME_HANDLE" ]; then
-  echo "No new ScummVM game found in $GAME_FOLDER - aborting."
-  exit 1
+if [ -z "$GAME_HANDLES_RAW" ]; then
+    echo "No new ScummVM game found in $GAME_FOLDER - aborting."
+    exit 1
 fi
 
-# Sanitize name to be used as scummvm file name
-GAME_NAME="$(sed -En "s/[ ]*Name:[ ]*(.*)/\1/p" <<< $ADDING_GAME_LOG)"
-SANITIZED_GAME_NAME="$(sed -e "s/[^()A-Za-z0-9 ._-]/ /g" <<< $GAME_NAME)"
+# Transform raw data into arrays (there could've been more than one game in this folder!)
+IFS=$'\n' GAME_HANDLES=($GAME_HANDLES_RAW)
+IFS=$'\n' GAME_NAMES=($GAME_NAMES_RAW)
 
-echo "Detected $GAME_NAME in $GAME_FOLDER and added the game as $GAME_HANDLE"
+for INDEX in "${!GAME_HANDLES[@]}"
+do
+    CURRENT_GAME_HANDLE=${GAME_HANDLES[$INDEX]}
+    CURRENT_GAME_NAME=${GAME_NAMES[$INDEX]}
 
-# Add the game also to the Standalone ScummVM configuration (and hide output)
-scummvm -c "$STANDALONE_SCUMMVM_INI" -p "$GAME_FOLDER" --add > /dev/null 2>&1;
+    # Sanitize name to be used as scummvm file name
+    SANITIZED_GAME_NAME="$(sed -e "s/[^()A-Za-z0-9 ._-]/ /g" <<< $CURRENT_GAME_NAME)"
 
-# Create *.scummvm file for EmulationStation
-echo "$GAME_HANDLE" > "$GAME_FOLDER/$SANITIZED_GAME_NAME.scummvm"
-echo "Created $GAME_FOLDER/$SANITIZED_GAME_NAME.scummvm"
+    echo "Detected $CURRENT_GAME_NAME in $GAME_FOLDER and added the game as $CURRENT_GAME_HANDLE"
+
+    # Add the game also to the Standalone ScummVM configuration (and hide output)
+    scummvm -c "$STANDALONE_SCUMMVM_INI" -p "$GAME_FOLDER" --add > /dev/null 2>&1;
+
+    # Create *.scummvm file for EmulationStation
+    echo "$CURRENT_GAME_HANDLE" > "$GAME_FOLDER/$SANITIZED_GAME_NAME.scummvm"
+    echo "Created $GAME_FOLDER/$SANITIZED_GAME_NAME.scummvm"
+
+done
 
 exit 0
